Security
Sergey113222/Cinema-Base-Gradle pull request #8
Opened 2022-02-16 14:28 UTC by Sergey113222

2022-02-17 09:06 UTC, MaksimMartsiusheu requested changes

2022-02-17 09:06 UTC, MaksimMartsiusheu commented on common/src/main/java/com/example/cinemabasegradle/dto/RoleDto.java
> +    @NotNull(message = "Name cannot be null")
Maybe `@NotBlank` will be better

2022-02-17 09:06 UTC, MaksimMartsiusheu commented on rest/src/main/java/com/example/cinemabasegradle/security/JwtTokenFilter.java
> +        filterChain.doFilter(request, response);
Mb let's add this line to `try` block?

2022-02-17 09:06 UTC, MaksimMartsiusheu commented on security/src/main/java/com/example/cinemabasegradle/service/JwtUserDetailsService.java
> +            throw new IllegalArgumentException(MESSAGE);
_"User doesn't exist"_  - I think that's not quite true. User exists, but passwords not match

2022-02-21 11:47 UTC, Sergey113222 commented on common/src/main/java/com/example/cinemabasegradle/dto/RoleDto.java
> +    @NotNull(message = "Name cannot be null")
done

2022-02-21 11:47 UTC, Sergey113222 commented on rest/src/main/java/com/example/cinemabasegradle/security/JwtTokenFilter.java
> +        filterChain.doFilter(request, response);
done

2022-02-21 11:47 UTC, Sergey113222 commented on security/src/main/java/com/example/cinemabasegradle/service/JwtUserDetailsService.java
> +            throw new IllegalArgumentException(MESSAGE);
done

2022-02-22 15:01 UTC, merged